services:
  server:
    build: .
    restart: always
    depends_on:
      - database
    volumes:
      - .:/easygenerator
      - /easygenerator/node_modules 
    ports:
      - 5555:5555
    networks:
      - app_network

  database:
    image: mongo:7
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: easygenerator
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

  mongo-express:
    image: mongo-express
    container_name: mongo_express_container
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: easygenerator
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: database
    ports:
      - 8081:8081
    depends_on:
      - database
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data:
    driver: local