const MINIMUM_USER_NAME_LENGHT =3,
 MINIMUM_USER_PASSWORD_LENGHT =8,
 JWT_STRATEGY = 'jwt',
 ACCESS_TOKEN_LIFETIME='15m'

export {
    MINIMUM_USER_NAME_LENGHT,
    MINIMUM_USER_PASSWORD_LENGHT,
    JWT_STRATEGY,
    ACCESS_TOKEN_LIFETIME
}